folio-org/data-import-raml-storage

- examples/mod-source-record-manager/fileDto.sample
- examples/mod-source-record-manager/initJobExecutionsRqDto.sample
- examples/mod-source-record-manager/initJobExecutionsRsDto.sample
- schemas/dto/fileDto.json
- schemas/dto/initJobExecutionsRqDto.json
- schemas/dto/initJobExecutionsRsDto.json
- schemas/mod-source-record-storage/errorRecord.json
- schemas/mod-source-record-storage/parsedRecord.json
- schemas/mod-source-record-storage/sourceRecord.json
* Added schemas for SRM
* Removed metadata from source, error and parsed records
> MODSOURMAN-9 MODSOUCE-15

- examples/mod-source-record-manager/logCollectionDto.sample
- examples/mod-source-record-manager/logDto.sample
- schemas/dto/logCollectionDto.json
- schemas/dto/logDto.json
Log renamed to LogDto;
LogCollection renamed to LogCollectionDto;
Samples updated;
> Moved Log & LogCollection json schema to the dto package;

- examples/mod-source-record-manager/initJobExecutionsRqDto.sample
- examples/mod-source-record-manager/initJobExecutionsRsDto.sample
- examples/mod-source-record-manager/jobExecution.sample
- examples/mod-source-record-manager/jobExecutionCollection.sample
- examples/mod-source-record-manager/jobExecutionCollectionDto.sample
- schemas/dto/initJobExecutionsRqDto.json
- schemas/mod-source-record-manager/jobExecution.json
- schemas/mod-source-record-manager/status.json
* Added DRAFT status for JobExecution
* Added userId field to JobExecution and InitJobExecutionsRqDto
* Updated examples
> MODDATAIMP-50 Added DRAFT status and userId field to JobExecution

- examples/mod-source-record-manager/statusDto.sample
- schemas/dto/statusDto.json
- schemas/mod-source-record-manager/status.json
- schemas/mod-source-record-manager/uiStatus.json
* Renamed DRAFT status to FILE_UPLOADED
* Added PARENT status for parent_multiple JobExecution
* Added status DTO
> MODSOURMAN-41 

- Jenkinsfile
which specifically assesses only RAML JSON schema descriptions
>  FOLIO-1481 Use separate CI job runLintRamlSchema

- examples/mod-source-record-manager/jobExecution.sample
- examples/mod-source-record-manager/jobExecutionCollection.sample
- examples/mod-source-record-manager/processChunkingRqDto.sample
- schemas/dto/processChunkingRqDto.json
- schemas/mod-source-record-manager/jobExecution.json
Renamed 'profile' field to 'jobProfile' for proper class generation
Added sample data for the ProcessChunkingRqDto
> Apply JobProfile

- examples/mod-data-import/uploadDefinition.sample
- schemas/mod-data-import/fileDefinition.json
> deleted loaded field

- schemas/common/userPersonalInfo.json
* Added common schema to store user personal information with firstName, lastName, userName
* No samples required
> MODSOURMAN-63 - Use common schema to store user personal data

- schemas/common/userInfo.json
* Renamed UserPersonalInfo to UserInfo
> MODSOURMAN-63 - Renamed UserPersonalInfo to UserInfo

- examples/mod-data-import-converter-storage/mappingProfile.sample
- examples/mod-data-import-converter-storage/mappingProfileCollection.sample
- examples/mod-data-import-converter-storage/profileAssociation.sample
- schemas/mod-data-import-converter-storage/mappingProfile.json
- schemas/mod-data-import-converter-storage/profileAssociation.json
* Added schema 'profileAssociation' to describe the relationship between profiles
* Added 'mapped' field to the Mapping profile schema
> Moddiconv-13

- schemas/mod-data-import-converter-storage/profileAssociation.json
* Changed type of the 'order' field (in profileAssociation schema) from number to integer
> Changed type of the 'order' field from number to integer

- examples/mod-data-import-converter-storage/profileAssociation.sample
- examples/mod-data-import-converter-storage/profileAssociationCollection.sample
- schemas/mod-data-import-converter-storage/profileAssociationCollection.json
* Added collection for profile associations
* Added sample data
> Add collection for profile associations

- examples/mod-source-record-storage/recordCollection.sample
- schemas/dto/recordCollection.json
-added errorMessages to the recordCollection DTO
> MODSOURCE-55 Partial batch save for records

- examples/mod-data-import-converter-storage/actionProfile.sample
- examples/mod-data-import-converter-storage/actionProfileCollection.sample
- schemas/mod-data-import-converter-storage/actionProfile.json
[Spreadsheet which describes Action Profile schema and sample data](https://docs.google.com/spreadsheets/d/1bqm06gphuX-ljoVRsEIR4nZvK5TncMbmvYF1Lrr0xgk/edit#gid=737952887)
> MODDICONV-19 - Add sample Action Profile data

- examples/mod-source-record-storage/parsedRecordCollection.sample
- schemas/mod-source-record-storage/parsedRecordCollection.json
add error messages to parsedRecordCollection.json + updated the sample
> MODSOURCE-56 Partial batch update for parsed records

- examples/mod-data-import-converter-storage/mappingProfile.sample
- examples/mod-data-import-converter-storage/mappingProfileCollection.sample
- schemas/mod-data-import-converter-storage/mappingProfile.json
[spreadsheet of mappingProfile schema](https://docs.google.com/spreadsheets/d/1m_E5psqrWQFz0Qt853i-3Emyib2R0B_CuIRlVTfcmtI/edit#gid=1212064214)
> MODDICONV-22 - Add sample Field Mapping Profile data

- examples/mod-source-record-storage/recordBatch.sample
- schemas/dto/recordBatch.json
-added new schema recordBatch.json
-removed errorMessages field from recordCollection.json
> MODSOURCE-67 Remove 'errorMessages' from response to get records

- schemas/mod-data-import-converter-storage/actionProfile.json
- schemas/mod-data-import-converter-storage/jobProfile.json
- schemas/mod-data-import-converter-storage/mappingProfile.json
- schemas/mod-data-import-converter-storage/matchProfile.json
Updated profiles schemas for support loading and saving profiles with associations in one transaction
> MODDICONV-86 Create Batch Post API for Import Profiles save including Profile Associations

- examples/mod-data-import-converter-storage/actionProfile.sample
- examples/mod-data-import-converter-storage/jobProfile.sample
- examples/mod-data-import-converter-storage/mappingProfile.sample
- examples/mod-data-import-converter-storage/matchProfile.sample
- examples/mod-data-import-converter-storage/profileSnapshotWrapper.sample
- schemas/mod-data-import-converter-storage/actionProfile.json
- schemas/mod-data-import-converter-storage/jobProfile.json
- schemas/mod-data-import-converter-storage/mappingProfile.json
- schemas/mod-data-import-converter-storage/matchProfile.json
- schemas/mod-data-import-converter-storage/profileAssociation.json
- schemas/mod-data-import-converter-storage/profileSnapshotWrapper.json
Create Batch GET API for Import Profiles retrieval including Profile Associations
> MODDICONV-90

- schemas/mod-data-import-converter-storage/entityType.json
Needed to support https://issues.folio.org/browse/UIDATIMP-351
> Added static value as an entityType for Profiles

- examples/mod-data-import-converter-storage/mapping-profile-detail/mappingDetail.sample
- examples/mod-data-import-converter-storage/mapping-profile-detail/mappingRule.sample
- schemas/mod-data-import-converter-storage/mapping-profile-detail/booleanFieldActions.json
- schemas/mod-data-import-converter-storage/mapping-profile-detail/mappingDetail.json
- schemas/mod-data-import-converter-storage/mapping-profile-detail/mappingRule.json
- schemas/mod-data-import-converter-storage/mapping-profile-detail/repeatableFieldActions.json
- schemas/mod-data-import-converter-storage/mappingProfile.json
Extend MappingProfile data structure with mappingDetails section
> MODDICONV-98

- schemas/mod-data-import-converter-storage/mapping-profile-detail/mappingRule.json
- schemas/mod-data-import-converter-storage/mapping-profile-detail/repeatableSubfieldMapping.json
In scope of story MODDICONV-103 I fixed mapping rules (corrected javaType).
> MODDICONV-103 Corrected javaType

- examples/mod-source-record-storage/record.sample
- schemas/mod-source-record-storage/recordModel.json
> MODSOURCE-114: Add State "field" to records table.

- schemas/dto/parsedRecordDto.json
Add source-record states storing mechanism for QM edit workflow
> MODSOURMAN-322

- schemas/common/externalIdsHolder.json
1."instanceHrid" field was added to the externalIdsHolder.json.
> MODDICORE-58: MARC-MARC matching for 001 and 999 ff fields

- examples/mod-data-import-converter-storage/mappingProfile.sample
- schemas/mod-data-import-converter-storage/mappingProfile.json
"marcFieldProtectionSettings" added to the mappingProfile.json
> MODDICONV-142: Extend MappingProfile data structure with field protection overwrites 

- examples/mod-source-record-manager/journalRecord.sample
- schemas/mod-source-record-manager/journalRecord.json
1. "title" field added to the "journalRecord.json".
> MODSOURMAN-380: Expand journalRecord entity with "title" property.

- examples/mod-source-record-storage/sourceRecordSearchRequest.sample
- schemas/dto/sourceRecordSearchRequest.json
**Purpose**
https://issues.folio.org/browse/MODSOURCE-228
In this story we need to come up with a contract for expressions used in a POST request needed for the search
> MODSOURCE-228-222

- examples/mod-source-record-storage/sourceRecordSearchRequest.sample
- schemas/dto/sourceRecordSearchRequest.json
Overview 
The changes are related to https://issues.folio.org/browse/MODSOURCE-223
* Changed data type from number(double) to integer
* Updated sample file with the latest version of syntax
> MODSOURCE-223 - changed data type for offset and limit

- examples/mod-source-record-manager/jobMonitoring.sample
- schemas/mod-source-record-manager/jobMonitoring.json
**Purpose** 
- Add new schema for JobMonitoring entity, added sample file
> MODSOURMAN-458 Support monitoring table creation and data insertion

- examples/mod-data-import-converter-storage/jobProfile.sample
- examples/mod-data-import-converter-storage/jobProfileCollection.sample
- examples/mod-data-import/dataImportEventPayload.sample
- examples/mod-source-record-manager/jobExecution.sample
- examples/mod-source-record-manager/processFilesRqDto.sample
- schemas/common/dataType.json
This story is an entry point for https://issues.folio.org/browse/MODDICORE-157. The data type should be returned to generic MARC instead of specific differentiation.
* changed data type to generic MARC
> MODDICORE-157 - Change dataType to have have common type for MARC related subtypes

- schemas/common/externalIdsHolder.json
##Purpose
Add holdings IDs to externalHoldingsIds
> MODSOURCE-343 Add holdings IDs

- schemas/mod-data-import-converter-storage/actionProfile.json
For this task we need add Authority folioRecord to ActionProfile
[MODDICONV-209](https://issues.folio.org/browse/MODDICONV-209)
[Pull request](https://github.com/folio-org/mod-data-import-converter-storage/pull/181)
> MODDICONV-209 Add AUTHORITY folioRecord

- schemas/dto/parsedRecordDto.json
Extend parsed record by filed for optimistic locking
Add version for parsedRecordDto 
https://issues.folio.org/browse/MODQM-167
> MODQM-167 - Optimistic locking: mod-quick-marc modifications (add version for parsedRecordDto)

- schemas/mod-data-import-converter-storage/entityType.json
Fix an error when deserializing mapping profiles with AUTHORITY EntityType
- Added the value "AUTHORITY" to EntityType enum
[MODDICONV-213](https://issues.folio.org/browse/MODDICONV-213)
> MODDICONV-213 Response on GET all mapping profiles returns null in a collection

- schemas/common/externalIdsHolder.json
Add authority ids to externalIdsHolder
> MODQM-159 Add authority ids to externalIdsHolder

- schemas/mod-data-import-converter-storage/actionProfile.json
- schemas/mod-data-import-converter-storage/jobProfile.json
- schemas/mod-data-import-converter-storage/mappingProfile.json
- schemas/mod-data-import-converter-storage/matchProfile.json
Make MARC Authority Delete profiles hidden
Extend job, match, action, mapping profiles schemas with new field:
* name: hidden
* type: boolean
* default: false
[MODDICONV-234](https://issues.folio.org/browse/MODDICONV-234)
> MODDICONV-234 Suppress MARC Authority Delete profiles from Data Import Settings UI

- schemas/common/profileInfo.json
Extend JobProfileInfo with new field
name: hidden
type: boolean
default: false
> MODSOURMAN-707 Extend profileInfo schema

- schemas/mod-data-import-converter-storage/actionProfile.json
- schemas/mod-data-import-converter-storage/jobProfile.json
- schemas/mod-data-import-converter-storage/mappingProfile.json
- schemas/mod-data-import-converter-storage/matchProfile.json
- schemas/mod-data-import-converter-storage/profileAssociation.json
All current errors arise from incorrect Boolean values.
- Removed quotes from incorrec boolean values.
[MODDICONV-239](https://issues.folio.org/browse/MODDICONV-239)
> MODDICONV-239 Migrate to use new api-lint and api-doc CI tools

- examples/mod-source-record-manager/jobExecution.sample
All current errors arise from one broken JSON sample record which has missing comma.
- Added forgotten quote
[MODSOURMAN-776](https://issues.folio.org/browse/MODSOURMAN-776)
> MODSOURMAN-776 Migrate to use new api-lint and api-doc CI tools

- examples/mod-source-record-manager/jobExecutionSummaryDto.sample
- schemas/dto/entityProcessingSummary.json
- schemas/dto/jobExecutionSummaryDto.json
to provide data of work accomplished in import job for the summary section of the logs page
[MODSOURMAN-780](https://issues.folio.org/browse/MODSOURMAN-780)
> MODSOURMAN-780 - Added job summary DTO schema

- schemas/dto/jobExecutionUserInfo.json
- schemas/dto/jobExecutionUserInfoCollection.json
> MODSOURMAN-790: Implement endpoint to get job executions users.

- schemas/mod-entities-links/bibAuthorityLinksUpdate.json
- schemas/mod-source-record-storage/marcBibUpdate.json
Add incoming and outgoing entities
[MODSOURCE-550](https://issues.folio.org/browse/MODSOURCE-550)
> MODSOURCE-550 Link update: Update MARC bibs according to links.instance-authority event

- schemas/mod-entities-links/instanceLinkDtoCollection.json
Add necessary dtos
- Add instanceLinkDtoCollection.json to raml-storage
[MODDICORE-293](https://issues.folio.org/browse/MODDICORE-293)
> MODDICORE-293 Handle bib-authority link when user updates a bib record via data import

- schemas/mod-source-record-storage/linkUpdateReport.json
- schemas/mod-source-record-storage/marcBibUpdate.json
> MODSOURCE-567 Link update report: add schemas

- schemas/dto/jobExecutionSummaryDto.json
- schemas/dto/jobLogEntryDto.json
- schemas/dto/recordProcessingLogDto.json
Added new fields for "poLine" entity 
Jira: https://issues.folio.org/browse/MODSOURMAN-932
> [MODSOURMAN-932] Extend logs DTOs with new poLine entity type

- schemas/mod-data-import-converter-storage/entityType.json
Added PO_LINE entity for usage in mod-inventory
Jira: https://issues.folio.org/browse/MODINV-774
> Added PO_LINE entity type

- schemas/mod-data-import-converter-storage/mapping-profile-detail/mappingRule.json
Added required field to mappingRule to validate productId in di-core
> [MODDICORE-306] Add optional required field to mappingRule

- schemas/mod-entities-links/instanceLinkDtoCollection.json
- schemas/mod-entities-links/linkingRuleDto.json
###Purpose
Add LinkingRule class and edit InstanceLinkCollection
##Approach
Added LinkingRuleDto json schema
##Learning
[https://issues.folio.org/browse/MODDICORE-320](https://issues.folio.org/browse/MODDICORE-320)
> MODDICORE-320: Changed instanceLink DTO according to recent changes

- schemas/mod-entities-links/instanceLinkDtoCollection.json
- schemas/mod-entities-links/linkingRuleDto.json
[MODDICORE-320](https://issues.folio.org/browse/MODDICORE-320)
> MODDICORE-320: Corrected LinkingRuleDto structure

- schemas/mod-entities-links/linkingRuleDto.json
- update linkingRuleDto.json schema to generate java `Map`
> MODDICORE-338 Update of "MARC Bib" record completed with error

- examples/mod-data-import-converter-storage/actionProfile.sample
- schemas/mod-data-import-converter-storage/actionProfile.json
Add flag for Action profiles to indicate $9 subfield removal
- add $9 removal flag
[MODDICONV-301](https://issues.folio.org/browse/MODDICONV-301)
> MODDICONV-301 MARC bib $9 handling | Add flag to indicate $9 subfield removal

- schemas/dto/strippedParsedRecord.json
See https://github.com/folio-org/mod-source-record-storage/pull/552
> Add OLD state for StrippedParsedRecord dto

- schemas/dto/assembleFileDto.json
add a DTO for the assemble file api
> Moddataimp 874 implement api to combine s3 multi part uploads

- examples/mod-source-record-manager/incomingRecord.sample
- schemas/mod-source-record-manager/incomingRecord.json
- schemas/mod-source-record-manager/journalRecord.json
[MODSOURMAN-1020](https://issues.folio.org/browse/MODSOURMAN-1020)
**Follow-up PR**: https://github.com/folio-org/mod-source-record-manager/pull/819
Add schemas for IncomingRecord
> MODSOURMAN-1020: add schemas for IncomingRecord

- schemas/dto/recordProcessingLogDto.json
- schemas/dto/recordProcessingLogDtoCollection.json
[MODSOURMAN-1063](https://issues.folio.org/browse/MODSOURMAN-1063)
> MODSOURMAN-1063: adjust recordProcessingLogDto.json and add recordProcessingLogDtoCollection.json schema

- schemas/dto/recordProcessingLogDto.json
Fix incomingRecordID title at recordProcessingLogDto.json
> [MODSOURMAN-1141] Fix incomingRecordID title at recordProcessingLogDto.json

- schemas/dto/recordMatchingRqDto.json
Add value for the qualifier in the recordMatchingRequestDto.
[MODSOURCE-783](https://folio-org.atlassian.net/browse/MODSOURCE-783)
> MODSOURCE-783 Extend MARC-MARC search query to account for qualifiers

- examples/mod-data-import-converter-storage/actionProfile.sample
- examples/mod-data-import-converter-storage/actionProfileCollection.sample
- examples/mod-data-import-converter-storage/actionProfileUpdateDto.sample
- examples/mod-data-import-converter-storage/jobProfile.sample
- examples/mod-data-import-converter-storage/jobProfileCollection.sample
- examples/mod-data-import-converter-storage/jobProfileUpdateDto.sample
- examples/mod-data-import-converter-storage/mappingProfile.sample
- examples/mod-data-import-converter-storage/mappingProfileCollection.sample
- examples/mod-data-import-converter-storage/mappingProfileUpdateDto.sample
- examples/mod-data-import-converter-storage/matchProfile.sample
- examples/mod-data-import-converter-storage/matchProfileCollection.sample
- examples/mod-data-import-converter-storage/matchProfileUpdateDto.sample
- schemas/mod-data-import-converter-storage/actionProfile.json
- schemas/mod-data-import-converter-storage/jobProfile.json
- schemas/mod-data-import-converter-storage/mappingProfile.json
- schemas/mod-data-import-converter-storage/matchProfile.json
Remove 'deleted' property from data import profiles
> [MODDICONV-388] Remove 'deleted' property from data import profiles
